config/routes.rb
CourseScope::Application.routes.draw do
  resources :terms

  resources :subjects

  resources :careers

  resources :descriptions

  resources :ctecs

  resources :classrooms

  resources :user_reviews

  resources :users

  resources :professors

  resources :courses

end

app/models/career.rb
class Career < ActiveRecord::Base
	has_and_belongs_to_many :courses
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	belongs_to :course
	belongs_to :user
	has_one :user, foreign_key: "user_id"
	has_one :course, foreign_key: "course_id"
end

app/models/course.rb
class Course < ActiveRecord::Base
	self.primary_key = "course_id"
	has_and_belongs_to_many :professors
	has_and_belongs_to_many :careers
	has_many :ctecs
	has_many :user_reviews
	has_many :users, through: :classrooms
	has_one :description, foreign_key: "course_id"
end

app/models/ctec.rb
class Ctec < ActiveRecord::Base
	has_one :course, foreign_key: "course_id"
	belongs_to :course
end

app/models/description.rb
class Description < ActiveRecord::Base
	belongs_to :course
end

app/models/professor.rb
class Professor < ActiveRecord::Base
	
	has_and_belongs_to_many :courses

end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/models/term.rb
class Term < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :user_reviews
	has_many :courses, through: :classrooms
end

app/models/user_review.rb
class UserReview < ActiveRecord::Base
	has_one :user, foreign_key: "user_id"
	has_one :course, foreign_key: "course_id"
	belongs_to :user
	belongs_to :course
end

app/controllers/user_reviews_controller.rb
class UserReviewsController < ApplicationController
  before_action :set_user_review, only: [:show, :edit, :update, :destroy]

  # GET /user_reviews
  # GET /user_reviews.json
  def index
    @user_reviews = UserReview.all
  end

  # GET /user_reviews/1
  # GET /user_reviews/1.json
  def show
  end

  # GET /user_reviews/new
  def new
    @user_review = UserReview.new
  end

  # GET /user_reviews/1/edit
  def edit
  end

  # POST /user_reviews
  # POST /user_reviews.json
  def create
    @user_review = UserReview.new(user_review_params)

    respond_to do |format|
      if @user_review.save
        format.html { redirect_to @user_review, notice: 'User review was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_review }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_reviews/1
  # PATCH/PUT /user_reviews/1.json
  def update
    respond_to do |format|
      if @user_review.update(user_review_params)
        format.html { redirect_to @user_review, notice: 'User review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_reviews/1
  # DELETE /user_reviews/1.json
  def destroy
    @user_review.destroy
    respond_to do |format|
      format.html { redirect_to user_reviews_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_review
      @user_review = UserReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_review_params
      params.require(:user_review).permit(:user_ID, :course_ID, :rating, :review)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/cte_cs_helper.rb
module CteCsHelper
end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/user_reviews_helper.rb
module UserReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user_reviews/_form.html.erb
<%= form_for(@user_review) do |f| %>
  <% if @user_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_review.errors.count, "error") %> prohibited this user_review from being saved:</h2>

      <ul>
      <% @user_review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_ID %><br>
    <%= f.number_field :user_ID %>
  </div>
  <div class="field">
    <%= f.label :course_ID %><br>
    <%= f.number_field :course_ID %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :review %><br>
    <%= f.text_area :review %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_reviews/edit.html.erb
<h1>Editing user_review</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_review %> |
<%= link_to 'Back', user_reviews_path %>

app/views/user_reviews/index.html.erb
<h1>Listing user_reviews</h1>

<table>
  <thead>
    <tr>
      <th>User id</th>
      <th>Course id</th>
      <th>Rating</th>
      <th>Review</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_reviews.each do |user_review| %>
      <tr>
        <td><%= user_review.user_ID %></td>
        <td><%= user_review.course_ID %></td>
        <td><%= user_review.rating %></td>
        <td><%= user_review.review %></td>
        <td><%= link_to 'Show', user_review %></td>
        <td><%= link_to 'Edit', edit_user_review_path(user_review) %></td>
        <td><%= link_to 'Destroy', user_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User review', new_user_review_path %>

app/views/user_reviews/new.html.erb
<h1>New user_review</h1>

<%= render 'form' %>

<%= link_to 'Back', user_reviews_path %>

app/views/user_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User id:</strong>
  <%= @user_review.user_ID %>
</p>

<p>
  <strong>Course id:</strong>
  <%= @user_review.course_ID %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @user_review.rating %>
</p>

<p>
  <strong>Review:</strong>
  <%= @user_review.review %>
</p>

<%= link_to 'Edit', edit_user_review_path(@user_review) %> |
<%= link_to 'Back', user_reviews_path %>