config/routes.rb
CourseScope::Application.routes.draw do
  resources :terms

  resources :subjects

  resources :careers

  resources :descriptions

  resources :ctecs

  resources :classrooms

  resources :user_reviews

  resources :users

  resources :professors

  resources :courses

end

app/models/career.rb
class Career < ActiveRecord::Base
	has_and_belongs_to_many :courses
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	belongs_to :course
	belongs_to :user
	has_one :user, foreign_key: "user_id"
	has_one :course, foreign_key: "course_id"
end

app/models/course.rb
class Course < ActiveRecord::Base
	self.primary_key = "course_id"
	has_and_belongs_to_many :professors
	has_and_belongs_to_many :careers
	has_many :ctecs
	has_many :user_reviews
	has_many :users, through: :classrooms
	has_one :description, foreign_key: "course_id"
end

app/models/ctec.rb
class Ctec < ActiveRecord::Base
	has_one :course, foreign_key: "course_id"
	belongs_to :course
end

app/models/description.rb
class Description < ActiveRecord::Base
	belongs_to :course
end

app/models/professor.rb
class Professor < ActiveRecord::Base
	
	has_and_belongs_to_many :courses

end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/models/term.rb
class Term < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :user_reviews
	has_many :courses, through: :classrooms
end

app/models/user_review.rb
class UserReview < ActiveRecord::Base
	has_one :user, foreign_key: "user_id"
	has_one :course, foreign_key: "course_id"
	belongs_to :user
	belongs_to :course
end

app/controllers/ctecs_controller.rb
class CtecsController < ApplicationController
  before_action :set_ctec, only: [:show, :edit, :update, :destroy]

  # GET /ctecs
  # GET /ctecs.json
  def index
    @ctecs = Ctec.all
  end

  # GET /ctecs/1
  # GET /ctecs/1.json
  def show
  end

  # GET /ctecs/new
  def new
    @ctec = Ctec.new
  end

  # GET /ctecs/1/edit
  def edit
  end

  # POST /ctecs
  # POST /ctecs.json
  def create
    @ctec = Ctec.new(ctec_params)

    respond_to do |format|
      if @ctec.save
        format.html { redirect_to @ctec, notice: 'Ctec was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ctec }
      else
        format.html { render action: 'new' }
        format.json { render json: @ctec.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ctecs/1
  # PATCH/PUT /ctecs/1.json
  def update
    respond_to do |format|
      if @ctec.update(ctec_params)
        format.html { redirect_to @ctec, notice: 'Ctec was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ctec.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ctecs/1
  # DELETE /ctecs/1.json
  def destroy
    @ctec.destroy
    respond_to do |format|
      format.html { redirect_to ctecs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ctec
      @ctec = Ctec.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ctec_params
      params.require(:ctec).permit(:course_ID, :description, :instr_rating, :course_rating, :learned_rating, :challenging_rating, :interest_rating, :school, :class, :reason, :interest_before)
    end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :set_term, only: [:show, :edit, :update, :destroy]

  # GET /terms
  # GET /terms.json
  def index
    @terms = Term.all
  end

  # GET /terms/1
  # GET /terms/1.json
  def show
  end

  # GET /terms/new
  def new
    @term = Term.new
  end

  # GET /terms/1/edit
  def edit
  end

  # POST /terms
  # POST /terms.json
  def create
    @term = Term.new(term_params)

    respond_to do |format|
      if @term.save
        format.html { redirect_to @term, notice: 'Term was successfully created.' }
        format.json { render action: 'show', status: :created, location: @term }
      else
        format.html { render action: 'new' }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /terms/1
  # PATCH/PUT /terms/1.json
  def update
    respond_to do |format|
      if @term.update(term_params)
        format.html { redirect_to @term, notice: 'Term was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terms/1
  # DELETE /terms/1.json
  def destroy
    @term.destroy
    respond_to do |format|
      format.html { redirect_to terms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_term
      @term = Term.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def term_params
      params.require(:term).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/cte_cs_helper.rb
module CteCsHelper
end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/user_reviews_helper.rb
module UserReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ctecs/_form.html.erb
<%= form_for(@ctec) do |f| %>
  <% if @ctec.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ctec.errors.count, "error") %> prohibited this ctec from being saved:</h2>

      <ul>
      <% @ctec.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_ID %><br>
    <%= f.number_field :course_ID %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :instr_rating %><br>
    <%= f.number_field :instr_rating %>
  </div>
  <div class="field">
    <%= f.label :course_rating %><br>
    <%= f.number_field :course_rating %>
  </div>
  <div class="field">
    <%= f.label :learned_rating %><br>
    <%= f.number_field :learned_rating %>
  </div>
  <div class="field">
    <%= f.label :challenging_rating %><br>
    <%= f.number_field :challenging_rating %>
  </div>
  <div class="field">
    <%= f.label :interest_rating %><br>
    <%= f.number_field :interest_rating %>
  </div>
  <div class="field">
    <%= f.label :school %><br>
    <%= f.text_field :school %>
  </div>
  <div class="field">
    <%= f.label :class %><br>
    <%= f.text_field :class %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_field :reason %>
  </div>
  <div class="field">
    <%= f.label :interest_before %><br>
    <%= f.number_field :interest_before %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ctecs/edit.html.erb
<h1>Editing ctec</h1>

<%= render 'form' %>

<%= link_to 'Show', @ctec %> |
<%= link_to 'Back', ctecs_path %>

app/views/ctecs/index.html.erb
<h1>Listing ctecs</h1>

<table>
  <thead>
    <tr>
      <th>Course id</th>
      <th>Description</th>
      <th>Instr rating</th>
      <th>Course rating</th>
      <th>Learned rating</th>
      <th>Challenging rating</th>
      <th>Interest rating</th>
      <th>School</th>
      <th>Class</th>
      <th>Reason</th>
      <th>Interest before</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ctecs.each do |ctec| %>
      <tr>
        <td><%= ctec.course_ID %></td>
        <td><%= ctec.description %></td>
        <td><%= ctec.instr_rating %></td>
        <td><%= ctec.course_rating %></td>
        <td><%= ctec.learned_rating %></td>
        <td><%= ctec.challenging_rating %></td>
        <td><%= ctec.interest_rating %></td>
        <td><%= ctec.school %></td>
        <td><%= ctec.class %></td>
        <td><%= ctec.reason %></td>
        <td><%= ctec.interest_before %></td>
        <td><%= link_to 'Show', ctec %></td>
        <td><%= link_to 'Edit', edit_ctec_path(ctec) %></td>
        <td><%= link_to 'Destroy', ctec, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ctec', new_ctec_path %>

app/views/ctecs/new.html.erb
<h1>New ctec</h1>

<%= render 'form' %>

<%= link_to 'Back', ctecs_path %>

app/views/ctecs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course id:</strong>
  <%= @ctec.course_ID %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ctec.description %>
</p>

<p>
  <strong>Instr rating:</strong>
  <%= @ctec.instr_rating %>
</p>

<p>
  <strong>Course rating:</strong>
  <%= @ctec.course_rating %>
</p>

<p>
  <strong>Learned rating:</strong>
  <%= @ctec.learned_rating %>
</p>

<p>
  <strong>Challenging rating:</strong>
  <%= @ctec.challenging_rating %>
</p>

<p>
  <strong>Interest rating:</strong>
  <%= @ctec.interest_rating %>
</p>

<p>
  <strong>School:</strong>
  <%= @ctec.school %>
</p>

<p>
  <strong>Class:</strong>
  <%= @ctec.class %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @ctec.reason %>
</p>

<p>
  <strong>Interest before:</strong>
  <%= @ctec.interest_before %>
</p>

<%= link_to 'Edit', edit_ctec_path(@ctec) %> |
<%= link_to 'Back', ctecs_path %>

app/views/terms/_form.html.erb
<%= form_for(@term) do |f| %>
  <% if @term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@term.errors.count, "error") %> prohibited this term from being saved:</h2>

      <ul>
      <% @term.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/terms/edit.html.erb
<h1>Editing term</h1>

<%= render 'form' %>

<%= link_to 'Show', @term %> |
<%= link_to 'Back', terms_path %>

app/views/terms/index.html.erb
<h1>Listing terms</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @terms.each do |term| %>
      <tr>
        <td><%= term.title %></td>
        <td><%= link_to 'Show', term %></td>
        <td><%= link_to 'Edit', edit_term_path(term) %></td>
        <td><%= link_to 'Destroy', term, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Term', new_term_path %>

app/views/terms/new.html.erb
<h1>New term</h1>

<%= render 'form' %>

<%= link_to 'Back', terms_path %>

app/views/terms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @term.title %>
</p>

<%= link_to 'Edit', edit_term_path(@term) %> |
<%= link_to 'Back', terms_path %>