config/routes.rb
CourseScope::Application.routes.draw do
  resources :terms

  resources :subjects

  resources :careers

  resources :descriptions

  resources :ctecs

  resources :classrooms

  resources :user_reviews

  resources :users

  resources :professors

  resources :courses

end

app/models/career.rb
class Career < ActiveRecord::Base
	has_and_belongs_to_many :courses
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	belongs_to :course
	belongs_to :user
	has_one :user, foreign_key: "user_id"
	has_one :course, foreign_key: "course_id"
end

app/models/course.rb
class Course < ActiveRecord::Base
	self.primary_key = "course_id"
	has_and_belongs_to_many :professors
	has_and_belongs_to_many :careers
	has_many :ctecs
	has_many :user_reviews
	has_many :users, through: :classrooms
	has_one :description, foreign_key: "course_id"
end

app/models/ctec.rb
class Ctec < ActiveRecord::Base
	has_one :course, foreign_key: "course_id"
	belongs_to :course
end

app/models/description.rb
class Description < ActiveRecord::Base
	belongs_to :course
end

app/models/professor.rb
class Professor < ActiveRecord::Base
	
	has_and_belongs_to_many :courses

end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/models/term.rb
class Term < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :user_reviews
	has_many :courses, through: :classrooms
end

app/models/user_review.rb
class UserReview < ActiveRecord::Base
	has_one :user, foreign_key: "user_id"
	has_one :course, foreign_key: "course_id"
	belongs_to :user
	belongs_to :course
end

app/controllers/ctecs_controller.rb
class CtecsController < ApplicationController
  before_action :set_ctec, only: [:show, :edit, :update, :destroy]

  # GET /ctecs
  # GET /ctecs.json
  def index
    @ctecs = Ctec.all
  end

  # GET /ctecs/1
  # GET /ctecs/1.json
  def show
  end

  # GET /ctecs/new
  def new
    @ctec = Ctec.new
  end

  # GET /ctecs/1/edit
  def edit
  end

  # POST /ctecs
  # POST /ctecs.json
  def create
    @ctec = Ctec.new(ctec_params)

    respond_to do |format|
      if @ctec.save
        format.html { redirect_to @ctec, notice: 'Ctec was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ctec }
      else
        format.html { render action: 'new' }
        format.json { render json: @ctec.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ctecs/1
  # PATCH/PUT /ctecs/1.json
  def update
    respond_to do |format|
      if @ctec.update(ctec_params)
        format.html { redirect_to @ctec, notice: 'Ctec was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ctec.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ctecs/1
  # DELETE /ctecs/1.json
  def destroy
    @ctec.destroy
    respond_to do |format|
      format.html { redirect_to ctecs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ctec
      @ctec = Ctec.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ctec_params
      params.require(:ctec).permit(:course_ID, :description, :instr_rating, :course_rating, :learned_rating, :challenging_rating, :interest_rating, :school, :class, :reason, :interest_before)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render action: 'show', status: :created, location: @subject }
      else
        format.html { render action: 'new' }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:subject, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/cte_cs_helper.rb
module CteCsHelper
end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/user_reviews_helper.rb
module UserReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<h1>Listing subjects</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.subject %></td>
        <td><%= subject.title %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @subject.subject %>
</p>

<p>
  <strong>Title:</strong>
  <%= @subject.title %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>